version: "3"
services:
 
  nginx_proxy:
    image: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/sites-enabled/:/etc/nginx/sites-enabled
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/cron/developer-crontab:/etc/cron.d/developer-crontab
      - ./proxy/cron/cron.sh:/tmp/cron.sh
      - ./proxy/cron/cron.log:/tmp/cron.log
      - ./proxy/cron/check_nginx.php:/tmp/check_nginx.php
      - ./proxy/certs:/etc/nginx/certs
    networks:
     - demo_webnet
     - prod_webnet
  
networks:
  demo_webnet:
  prod_webnet:
